### ISSUE TITLE
fallback for browsers that don't support contain property

### ISSUE THREAD

**Issue by bennypowers** [zerodevx/zero-md#13]
Please see https://github.com/ruphin/slidem/issues/4#issuecomment-480543521

tl;dr: zero-md should add `overflow:auto` before `contain: content` in `_buildStyles` to support browsers that don't have the `contain` CSS property.

**Comment by zerodevx** [comment]
Thanks - I replied over here: https://github.com/ruphin/slidem/issues/4#issuecomment-480593196

I'm not sure if `overflow:auto` is the right fallback for `contain:content` though. But since `contain:content` is non-standard, we should maybe remove it so that behaviour is synchronised across browsers.

**Comment by bennypowers** [comment]
position: relative is probably a sensible default for the element's `:host` in any event, and it does solve the problem of stacking context.

**Comment by zerodevx** [comment]
Agreed - a `display: block; position: relative; contain: content;` are sensible defaults that helps mitigate stacking issues for non-Chrome browsers.

Fixed in https://github.com/zerodevx/zero-md/pull/14/commits/511d91b94ea9d796d24b781d85b3978473465a6f

**Comment by bennypowers** [comment]
Thank you
