### ISSUE TITLE
Anchors in Markdown

### ISSUE THREAD

**Issue by alexroseb** [zerodevx/zero-md#4]
Anchor links aren't working. I see in the code that headers have id's properly (without needing to manually implement them, nice!) but when I put anchors up in a table of contents the links don't do anything. I even tried adding manual anchors using HTML in my md but it still didn't do anything.

**Comment by zerodevx** [comment]
Good issue - thanks for raising this!

I guess in a sense, this is expected behaviour (as the adage goes, it's a feature, not a bug) - because the generated HTML is stamped into its own shadow DOM and hence "protected" from the outside... Anchor links work by pointing to an element's `id`, of which the document is unable to find because it's encapsulated.

But you raised a very good point. I'll do a PR to add this feature.

In the meantime, as a workaround, try setting the `no-shadow` attribute and see if it works.

For example,
```html
<zero-md src="..." no-shadow></zero-md>
```

**Comment by zerodevx** [comment]
And... done.

[v1.1.0](https://github.com/zerodevx/zero-md/releases/tag/v1.1.0) should support anchor links now.

**Comment by alexroseb** [comment]
Nice turnaround time! Works great now. Thank you!
