### ISSUE TITLE
this._resolve is not a function

### ISSUE THREAD

**Issue by jonmann20** [zerodevx/zero-md#45]
Having an issue when dispalying the component, than remvoing it where connectedCallback is fired after the resolve method is deleted (https://github.com/zerodevx/zero-md/blob/main/src/index.js#L71).  Maybe need to check if this exists before calling it?

```
Uncaught TypeError: this._resolve is not a function
    at HTMLElement.connectedCallback (index.js:70)
```

Here is my related code:
```js
import 'zero-md/dist/zero-md.min.js';   // could not import src since it tries to import a JSON file
// ...
render() {
       return html`
                ${this.item?.changelog && this.item?.changelog !== '' ? html`
                    <zero-md @zero-md-rendered="${() => this.dispatchEvent(new Event('notifyResize'))}">
                        <script type="text/markdown">${this.item?.changelog}</script>
                    </zero-md>
                ` : html`
                    <p>&mdash;</p>
                `}
       `
}
```
This component is shown in a dialog and on closing the dialog I get the error.

**Comment by zerodevx** [comment]
Hi - thanks for highlighting this. I believe it's a bug because I didn't handle the edge case whereby an instance may be disconnected, then reconnected again, without being re-instantiated.

Internally, there are 2 pre-requisites before `zero-md` can begin its rendering op:
1. Marked and Prism must be loaded; and
2. The instance must be connected.

The `waitForReady()` function basically ensures that these 2 conditions are met.

I'll try to think of a better way to handle this and roll-out a bug fix soon. At the same time, I'll remove the (non-standard) JSON import so that you should be able to consume via the recommended way:

```js
import ZeroMd from 'zero-md'

customElements.define('zero-md', ZeroMd)

render() {
  ...
}

```

 Thanks again!

**Comment by zerodevx** [comment]
Hi @jonmann20 - fixed it! Could you kindly help see if the issues are resolved? The latest version `v2.1.0-rc.1` is in pre-release so if you could run this:

```
npm i -D zero-md@next
```

then consume using:

```js
import ZeroMd from 'zero-md'

customElements.define('zero-md', ZeroMd)

render() {
  ...
}
```

and let me know if anything else crops up? 🙏

**Comment by jonmann20** [comment]
Worked perfect, thanks for the quick response!

**Comment by zerodevx** [comment]
Thanks for bringing this issue up! This should be fixed with [the latest release](https://github.com/zerodevx/zero-md/releases/tag/v2.1.0). I'll mark this issue as closed for now - but do re-open this if it happens again. 🍻
